/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:9122d65e-2a19-4c6d-a1a6-7de52fd8bc37",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_sDc7WXlrE",
    "aws_user_pools_web_client_id": "3cr4shpnidirbktl8bpim0hqp8",
    "oauth": {}
};


export default awsmobile;
