/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:9122d65e-2a19-4c6d-a1a6-7de52fd8bc37",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_sDc7WXlrE",
    "aws_user_pools_web_client_id": "3cr4shpnidirbktl8bpim0hqp8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fkgpntmutrabjdchoct7zopesi.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sij5ggzmknd4zir627cschaffm"
};


export default awsmobile;
